version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    profiles: ['ci', 'walla']
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432
